# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: TEST

on:
  pull_request:
    branches: [ master ]
  push:
    branches:
      - '*'
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'src/docs/**'

env:
  JAVA_VERSION: 17
  JAVA_DISTRIBUTION: 'temurin'

jobs:

  Lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew ktlintFormat --stacktrace
      - uses: stefanzweifel/git-auto-commit-action@v5
        if: always()
        with:
          commit_message: Ktlint format

  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [
          macos-13,
          ubuntu-latest,
          windows-latest
        ]
        experimental: [ false ]
        include:
          - os: macos-latest
            experimental: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew clean build assemble test -x jsBrowserTest --console=plain --stacktrace
